# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Verify the Rcpp / RcppArmadillo toolchain is wired up
#'
#' Internal stub used by Day 15's profiling script to confirm
#' the C++ compiler, Rcpp dispatch, and Armadillo linking all work
#' before the real ports on Days 16-18. Performs a trivial 3x3
#' identity-matrix trace to exercise the linker.
#'
#' @return A character string of the form
#'   "OK (Armadillo X.Y.Z; trace(I_3) = 3)".
#'
#' @keywords internal
#' @export
cevcmm_rcpp_check <- function() {
    .Call(`_cevcmm_cevcmm_rcpp_check`)
}

